#!/bin/bash

# set built-in default values
INSTALL_PREFIX=/usr/local
INSTALL_BIN_DIR=$INSTALL_PREFIX/bin
INSTALL_JAR_DIR=$INSTALL_PREFIX/share/java

# read default configuration
if [ -f /etc/installjar.conf ]; then
   . /etc/installjar.conf
fi

# override with user configuration
if [ -f $HOME/.installjarrc ]; then
   . $HOME/.installjarrc
fi

function create_wrapper() {
    cat < $INSTALL_PREFIX
}

while [ $# -gt 1]; do
  arg=$1

  case "$arg" in
      -p|--prefix)
	  shift
	  INSTALL_PREFIX=$1
          shift
	  ;;
  esac
done

jarfile=$1

install $jarfile $INSTALL_JAR_DIR
create_wrapper
